[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.ashley:ashley:$ashleyVersion"
  api "com.badlogicgames.box2dlights:box2dlights:$box2dlightsVersion"
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.crashinvaders.vfx:gdx-vfx-core:$gdxVfxCoreVersion"
  api "com.crashinvaders.vfx:gdx-vfx-effects:$gdxVfxEffectsVersion"
  api "com.github.MrStahlfelge.gdx-websockets:core:$websocketVersion"
  api "com.github.crykn.guacamole:core:$guacamoleVersion"
  api "com.github.crykn.guacamole:gdx:$guacamoleVersion"
  api "com.github.crykn:libgdx-screenmanager:$screenManagerVersion"
  api "com.github.tommyettinger:anim8-gdx:$anim8Version"
  api "com.github.tommyettinger:digital:$digitalVersion"
  api "com.github.tommyettinger:formic:$formicVersion"
  api "com.github.tommyettinger:libgdx-utils-box2d:$utilsBox2dVersion"
  api "com.github.tommyettinger:libgdx-utils:$utilsVersion"
  api "com.github.tommyettinger:sjInGameConsole:$inGameConsoleVersion"
  api "de.golfgl.gdxcontrollerutils:gdx-controllerutils-mapping:$controllerMappingVersion"
  api "de.golfgl.gdxcontrollerutils:gdx-controllerutils-scene2d:$controllerScene2DVersion"
  api "de.tomgrill.gdxdialogs:gdx-dialogs-core:$dialogsVersion"
  api "space.earlygrey:simple-graphs:$simpleGraphsVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
